### ISSUE TITLE
??

### ISSUE THREAD

**Issue by ebzrvf** [palera1n/palera1n#34] opened 2022-09-26 14:59 UTC
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

Hello, iPhone9,4 on 15.4.1!
[*] Switching device into recovery mode...
ERROR: Unable to connect to device
ebzrvf@ebzrvrf:~/Desktop/palera1n$

**Comment by itsnebulalol** [comment] 2022-09-26 14:59
Use sudo

**Comment by ebzrvf** [comment] 2022-09-26 15:00
> Use sudo

ok wait

**Comment by ebzrvf** [comment] 2022-09-26 15:00
> Use sudo
ebzrvf@ebzrvrf:~/Desktop/palera1n$ sudo ./palera1n.sh
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

Hello, iPhone9,4 on 15.4.1!
[*] Switching device into recovery mode...
ERROR: Unable to connect to device
ebzrvf@ebzrvrf:~/Desktop/palera1n$

**Comment by ebzrvf** [comment] 2022-09-26 15:01
> Use sudo

ebzrvf@ebzrvrf:~/Desktop/palera1n$ sudo ./palera1n.sh
palera1n | Version 1.0.0
Written by Nebula | Some code and ramdisk from Nathan | Patching commands and help from Mineek | Loader app by Amy

Hello, iPhone9,4 on 15.4.1!
[*] Switching device into recovery mode...
ERROR: Unable to connect to device
ebzrvf@ebzrvrf:~/Desktop/palera1n$

**Comment by ebzrvf** [comment] 2022-09-26 15:01
again again :(

**Comment by itsnebulalol** [comment] 2022-09-26 15:05
Run these:
```
sudo systemctl stop usbmuxd
sudo usbmuxd -p -f
```

**Comment by ebzrvf** [comment] 2022-09-26 15:09
maybe i have to install the another packages?? or what

**Comment by rubensalbukrk** [comment] 2022-09-26 15:27
try in mode dfu
`./palera1n.sh --dfu your ios version --debug`

**Comment by ebzrvf** [comment] 2022-09-26 15:38
> try in mode dfu `./palera1n.sh --dfu your ios version --debug`

it works but:

Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-7195 inputted
get_amfi_out_of_my_way_patch: Found entitlements too small str loc at 0x9015f7
get_amfi_out_of_my_way_patch: Found entitlements too small str ref at 0xfc6f30
get_amfi_out_of_my_way_patch: Patching AMFI at 0xfc1df8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
error: allocate
error: Success
[-] An error occurred
ebzrvf@ebzrvrf:~/Desktop/palera1n$

**Comment by rubensalbukrk** [comment] 2022-09-26 15:39
me too :D

**Comment by itsnebulalol** [comment] 2022-09-26 15:39
As I said in another issue, seems like an issue with hfsplus.

**Comment by ebzrvf** [comment] 2022-09-26 15:40
> Как я уже говорил в другом выпуске, похоже, проблема с hfsplus.

wait to fix

**Comment by rubensalbukrk** [comment] 2022-09-26 15:42
> 

I installed the package hfsplus too :D

**Comment by ebzrvf** [comment] 2022-09-26 15:43
> > 
> 
> I installed the package hfsplus too :D

me too :DDDDDDDDD

**Comment by itsnebulalol** [comment] 2022-09-26 15:48
Installing hfsplus won’t fix the issue since we use prebuilt binaries. If you want to try, you can remove `"$oscheck"/` from the hfsplus lines in `ramdisk/sshrd.sh`.

**Comment by ebzrvf** [comment] 2022-09-26 15:57
> Installing hfsplus won’t fix the issue since we use prebuilt binaries. If you want to try, you can remove `"$oscheck"/` from the hfsplus lines in `ramdisk/sshrd.sh`.

Ok thx i try it

**Comment by runhuizhou** [comment] 2022-09-26 16:19
> Installing hfsplus won’t fix the issue since we use prebuilt binaries. If you want to try, you can remove `"$oscheck"/` from the hfsplus lines in `ramdisk/sshrd.sh`.

./sshrd.sh: line 156: hfsplus: command not found

**Comment by itsnebulalol** [comment] 2022-09-26 16:25
Then you don’t have hfsplus installed

**Comment by runhuizhou** [comment] 2022-09-26 18:06
> Then you don’t have hfsplus installed

Thank you. I can't find hfsplus package for Arch Linux, so I just installed hfsplus package in Ubuntu guest machine, via "sudo apt install hfsplus", but terminal says "hfsplus: not found". 
Seems we cannot execute command like "hfsplus xxxxx" in Ubuntu.

**Comment by itsnebulalol** [comment] 2022-09-26 18:08
You need to compile it

https://github.com/planetbeing/libdmg-hfsplus

**Comment by runhuizhou** [comment] 2022-09-26 18:29
> You need to compile it
> 
> https://github.com/planetbeing/libdmg-hfsplus

Thank you so much. It works.

**Comment by rubensalbukrk** [comment] 2022-09-26 18:34
> You need to compile it
> 
> https://github.com/planetbeing/libdmg-hfsplus

i try now

**Comment by runhuizhou** [comment] 2022-09-26 18:44
> That fixed the error? Can you send the binary please

https://drive.google.com/file/d/1SK6BRjcYXjpADADyKGzR_QTCOGsP9rTQ/view?usp=sharing
Complied it and executed on Arch Linux

**Comment by rubensalbukrk** [comment] 2022-09-26 19:22
=========================>]
download succeeded
./sshrd.sh: 108: Syntax error: "then" unexpected
[-] An error occurred
rubens@rubensdev:~/palera1n$

**Comment by itsnebulalol** [comment] 2022-09-26 19:22
I replaced the binary with a known working one, @rubensalbukrk and @ebzrvf please reclone the repo and try again.

**Comment by rubensalbukrk** [comment] 2022-09-26 19:28
download succeeded
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0C ECID:000E415818EAED26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
usb_timeout: 5
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:0C ECID:000E415818EAED26 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[gaster]
Found the USB handle.
Now you can boot untrusted images.
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
main: Starting...
iOS 14 iBoot detected!
getting get_debug_enabled_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c2d88 : 000080d2
applying patch=0x1800c2ddc : 000080d2
applying patch=0x1800c4758 : 200080d2
main: Writing out patched file to work/iBSS.patched...
main: Quitting...
none
main: Starting...
iOS 14 iBoot detected!
getting get_boot_arg_patch(rd=md0 debug=0x2014e -v wdt=-1  ) patch
getting get_debug_enabled_patch() patch
getting get_unlock_nvram_patch() patch
getting get_sigcheck_patch() patch
applying patch=0x1800c2d88 : 000080d2
applying patch=0x1800c2ddc : 000080d2
applying patch=0x1800b38c8 : 000080d2c0035fd6
applying patch=0x1800b3918 : 000080d2c0035fd6
applying patch=0x1800f0d28 : 000080d2c0035fd6
applying patch=0x1800c4758 : 200080d2
applying patch=0x1800c5d38 : f9473430
applying patch=0x18012e635 : 72643d6d64302064656275673d30783230313465202d76207764743d2d31202000
applying patch=0x1800c8a14 : 1f2003d5
main: Writing out patched file to work/iBEC.patched...
main: Quitting...
none
krnl
main: Starting...
main: Detected fat macho kernel
Kernel: Adding AMFI_get_out_of_my_way patch...
get_amfi_out_of_my_way_patch: Entering ...
get_amfi_out_of_my_way_patch: Kernel-7195 inputted
get_amfi_out_of_my_way_patch: Found entitlements too small str loc at 0x9015f7
get_amfi_out_of_my_way_patch: Found entitlements too small str ref at 0xfc6f30
get_amfi_out_of_my_way_patch: Patching AMFI at 0xfc1df8
main: Writing out patched file to work/kcache.patched...
main: Quitting...
krnl
dtre
rtsc
rdsk
error: allocate
error: Success
[-] An error occurred

**Comment by itsnebulalol** [comment] 2022-09-26 19:31
> https://drive.google.com/file/d/1SK6BRjcYXjpADADyKGzR_QTCOGsP9rTQ/view?usp=sharing Complied it and executed on Arch Linux

Can you try and replace the hfsplus binary in ramdisk/Linux with this one

**Comment by rubensalbukrk** [comment] 2022-09-26 19:31
i compiled it [https://github.com/planetbeing/libdmg-hfsplus](url)
But I don't know if I did it right!

**Comment by rubensalbukrk** [comment] 2022-09-26 19:32
> Can you try and replace the hfsplus binary in ramdisk/Linux with this one

ok i try again

**Comment by rubensalbukrk** [comment] 2022-09-26 19:38
nice, working perfect!
:D :D :D

**Comment by rubensalbukrk** [comment] 2022-09-26 19:39
[*] Cleaning up work directory
[*] Booting ramdisk
[*] Getting device info... this may take a second
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[==================================================] 100.0%
[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting

**Comment by itsnebulalol** [comment] 2022-09-26 19:40
> nice, working perfect! :D :D :D

Pushed upstream

**Comment by itsnebulalol** [comment] 2022-09-26 19:40
> [_] Cleaning up work directory [_] Booting ramdisk [_] Getting device info... this may take a second [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [_] Device should now show text on screen [*] Waiting for the ramdisk to finish booting

Yes, did it return to prompt?

**Comment by runhuizhou** [comment] 2022-09-26 19:43
> [_] Cleaning up work directory [_] Booting ramdisk [_] Getting device info... this may take a second [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [_] Device should now show text on screen [*] Waiting for the ramdisk to finish booting

Mine was just stuck here, the device (2017 ipad pro 10.5) booted, i don't know if it jailbroke successfully. Tips app is still Tips.

**Comment by itsnebulalol** [comment] 2022-09-26 19:44
What system is this running on

**Comment by rubensalbukrk** [comment] 2022-09-26 19:44
> > [_] Cleaning up work directory [_] Booting ramdisk [_] Getting device info... this may take a second [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [_] Device should now show text on screen [*] Waiting for the ramdisk to finish booting
> 
> Mine was just stuck here, the device (2017 ipad pro 10.5) booted, i don't know if it jailbroke successfully. Tips app is still Tips.

me too :D

**Comment by runhuizhou** [comment] 2022-09-26 19:45
> > [_] Cleaning up work directory [_] Booting ramdisk [_] Getting device info... this may take a second [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [==================================================] 100.0% [_] Device should now show text on screen [*] Waiting for the ramdisk to finish booting
> 
> Mine was just stuck here, the device (2017 ipad pro 10.5) booted, i don't know if it jailbroke successfully. Tips app is still Tips.

iPadOS 15.7

**Comment by rubensalbukrk** [comment] 2022-09-26 19:46
> What system is this running on

iphone 7 15.4.1

**Comment by itsnebulalol** [comment] 2022-09-26 19:46
What Linux machine (and is it a VM/WSL)

**Comment by rubensalbukrk** [comment] 2022-09-26 19:47
no virtual...
linux mint lasted

**Comment by runhuizhou** [comment] 2022-09-26 19:47
OS: Arch Linux x86_64 
Kernel: 5.19.11-arch1-1 
local machine

**Comment by itsnebulalol** [comment] 2022-09-26 19:49
What happens when the progress bars show up? Does the device show the "blobs are dumping" image at all? Does verbose text appear? Does it show the normal apple logo? Do you see the block head ASCII art if it verboses?

**Comment by rubensalbukrk** [comment] 2022-09-26 19:51
yes yes, show

**Comment by itsnebulalol** [comment] 2022-09-26 19:52
What?

**Comment by rubensalbukrk** [comment] 2022-09-26 19:54
All this appears, then the apple logo with progress bar and starts!

**Comment by itsnebulalol** [comment] 2022-09-26 19:54
Can you show me a picture of the progress bar?

**Comment by rubensalbukrk** [comment] 2022-09-26 19:55
i record now, wait

**Comment by rubensalbukrk** [comment] 2022-09-26 20:10
First: 

https://user-images.githubusercontent.com/113955022/192370358-ef06ca3e-72c8-4f63-bb62-d4f1912d3285.MOV

after:

https://user-images.githubusercontent.com/113955022/192370398-50bbe618-d27e-4b68-bb1a-0cbae6ceae0a.MOV

**Comment by runhuizhou** [comment] 2022-09-26 20:16
Mine is similar. the progress bar looks like 0% forever
Whole video: https://drive.google.com/file/d/1UpixgUM51C-z7n27HhlciR6eTGM1WKqe/view?usp=sharing

**Comment by itsnebulalol** [comment] 2022-09-26 20:18
yep, seems like the ramdisk.tar.gz is messed up. ill look into this a bit more

**Comment by itsnebulalol** [comment] 2022-09-26 20:23
The issue is not in the ramdisk.tar.gz, it's either when it was decompressed, or hfsplus extracting it, or creating the dmg. I'll have to actually use a Linux device to debug.

**Comment by rubensalbukrk** [comment] 2022-09-26 20:29
I am available for testing, grateful for the work ^^

**Comment by itsnebulalol** [comment] 2022-09-27 00:15
@rubensalbukrk can you try and reclone the repo, then try again

**Comment by rubensalbukrk** [comment] 2022-09-27 01:23
> @rubensalbukrk can you try and reclone the repo, then try again

![IMG-20220926-WA1703](https://user-images.githubusercontent.com/113955022/192409428-5d610a75-ec61-4586-8aba-3f25c8bd5da0.jpeg)

Ficou congelado!

**Comment by itsnebulalol** [comment] 2022-09-27 01:24
Did the script continue?

**Comment by rubensalbukrk** [comment] 2022-09-27 01:27
> 

n0,
`[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting
`

**Comment by itsnebulalol** [comment] 2022-09-27 01:29
Oh okay, still closer.

Can you exit the script, and run `ssh root@localhost -p 2222`

If you get in, the password is `alpine`. Tell me if it works

**Comment by rubensalbukrk** [comment] 2022-09-27 01:30
> > 
> 
> n0, `[*] Device should now show text on screen [*] Waiting for the ramdisk to finish booting `



> ssh root@localhost -p 2222

in new terminal?

**Comment by rubensalbukrk** [comment] 2022-09-27 01:32
rubens@rubensdev:~/palera1n$ ssh root@localhost -p 2222
kex_exchange_identification: Connection closed by remote host
Connection closed by 127.0.0.1 port 2222
rubens@rubensdev:~/palera1n$

**Comment by itsnebulalol** [comment] 2022-09-27 01:33
Run these:
```
killall iproxy
sudo iproxy 2222 22 &
ssh root@localhost -p 2222
``'

**Comment by rubensalbukrk** [comment] 2022-09-27 01:38
`root@rubensdev:/home/rubens# sudo iproxy 2222 22
Creating listening port 2222 for device port 22
waiting for connection
New connection for 2222->22, fd = 5
waiting for connection
Connecting to usbmuxd failed, terminating.`

`root@rubensdev:/home/rubens/palera1n# ssh root@localhost -p 2222
kex_exchange_identification: Connection closed by remote host
Connection closed by 127.0.0.1 port 2222
root@rubensdev:/home/rubens/palera1n# 
`

**Comment by itsnebulalol** [comment] 2022-09-27 01:40
ah, open up another terminal and type these commands:
```
sudo systemctl stop usbmuxd
sudo usbmux -f -p
```
then try the 3 commands from before again

**Comment by rubensalbukrk** [comment] 2022-09-27 01:42
root@rubensdev:/home/rubens/palera1n# sudo systemctl stop usbmuxd
sudo usbmuxd -f -p
[22:39:15.591][3] usbmuxd v1.1.1 starting up
[22:39:15.592][3] Using libusb 1.0.25
[22:39:15.612][3] Initialization complete
[22:39:15.613][3] Connecting to new device on location 0x10022 as ID 1
[22:39:15.615][3] Connected to v2.0 device 1 on location 0x10022 with serial number ramdisk tool Sep 18 2022 20:14:43
[22:39:16.227][2] device_control_input: Got unhandled payload type 5

**Comment by rubensalbukrk** [comment] 2022-09-27 01:43
work:
rubens@rubensdev:~$ killall iproxy
sudo iproxy 2222 22 &
ssh root@localhost -p 2222
iproxy(86866): Operation not permitted
iproxy: no process found
[1] 87038
The authenticity of host '[localhost]:2222 ([127.0.0.1]:2222)' can't be established.
ECDSA key fingerprint is SHA256:lb9y8xaKPkXl5gUgA+WHH5TbDlRwWZ6Io7BBLbX+PuE.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[localhost]:2222' (ECDSA) to the list of known hosts.
root@localhost's password: 
localhost:~ root#

**Comment by rubensalbukrk** [comment] 2022-09-27 01:44
and now? :D

**Comment by itsnebulalol** [comment] 2022-09-27 01:49
Ok, good to know. I’m going to make a quick fix

**Comment by rubensalbukrk** [comment] 2022-09-27 01:52
done, i am waiting

**Comment by itsnebulalol** [comment] 2022-09-27 01:53
Ok, just made the fix, can you try and reclone the repo, then try again, then tell me if it works

**Comment by rubensalbukrk** [comment] 2022-09-27 01:56
Ok, lets go

**Comment by rubensalbukrk** [comment] 2022-09-27 02:14
Frozen in:
![20220926_231307](https://user-images.githubusercontent.com/113955022/192415580-89f1fe08-5ad8-45ee-9c26-afebcbd53f9d.jpg)

**Comment by itsnebulalol** [comment] 2022-09-27 02:15
How long has it been there, what does the computer say

**Comment by rubensalbukrk** [comment] 2022-09-27 02:17
10 min,
[*] Device should now show text on screen
[*] Waiting for the ramdisk to finish booting

**Comment by itsnebulalol** [comment] 2022-09-27 02:17
are you running the script as sudo

**Comment by rubensalbukrk** [comment] 2022-09-27 02:18
yes

**Comment by rubensalbukrk** [comment] 2022-09-27 02:19
`sudo ./palera1n.sh --dfu 15.4.1 --debug`

**Comment by itsnebulalol** [comment] 2022-09-27 02:20
can you `sudo su` then run it from there

**Comment by rubensalbukrk** [comment] 2022-09-27 02:54
![20220926_235313](https://user-images.githubusercontent.com/113955022/192420947-4e707abc-d723-4192-8ecf-8954e3776dfb.jpg)

Fronzen

**Comment by rubensalbukrk** [comment] 2022-09-27 03:02
Hey!!!!
Has continued after this:

https://user-images.githubusercontent.com/113955022/192422034-6e6d59b2-ffdf-4a97-94f9-85c4540242b2.MOV

**Comment by rubensalbukrk** [comment] 2022-09-27 03:06
The Tips not open

https://user-images.githubusercontent.com/113955022/192422422-d3330a15-eb46-433b-b586-a7e46914c77f.MOV

**Comment by rubensalbukrk** [comment] 2022-09-27 03:08
`
/home/rubens/palera1n/binaries/Linux/ideviceenterrecovery: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
`

replace the irecovery.zip?

**Comment by itsnebulalol** [comment] 2022-09-27 03:28
Actually no, you’ll want to install openssl 1.1
`curl -sL http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb -o libssl.deb && sudo apt install ./libssl.deb`

Since it continued, it’s practically done. It just needs to make the boot files. Sorry for the late response.

**Comment by rubensalbukrk** [comment] 2022-09-27 03:31
Ok, i try again , wait a moment … I'm having dinner this time :D 💪🏼 Create muscle’s

**Comment by rubensalbukrk** [comment] 2022-09-27 03:42
Sucess!!!!
All done!
👏👏👏👏🏼👏🏾👏🏽👏🏿

https://user-images.githubusercontent.com/113955022/192426681-f4184c74-9959-427c-87f8-855ed9323e42.MOV

**Comment by rubensalbukrk** [comment] 2022-09-27 03:47
![B3EB9BC5-95C1-432E-A340-88FF6EBE03F5](https://user-images.githubusercontent.com/113955022/192427349-f2367e77-a8d7-48e0-9b65-ccd992e660d3.png)

**Comment by rubensalbukrk** [comment] 2022-09-27 03:51
![Uploading A3E1EBA1-5E67-4972-8290-ABA8CBE87AB2.png…]()

**Comment by rubensalbukrk** [comment] 2022-09-27 03:56
![5C8162BC-6E6E-468D-BED3-6DF6F93FFA72](https://user-images.githubusercontent.com/113955022/192428451-3fe51c66-5fbf-461d-86b2-f2deacbb548c.png)

**Comment by rubensalbukrk** [comment] 2022-09-27 04:09
iPhone 7 GSM 15.4.1 works :D

**Closed** 2022-09-27 17:52 UTC
