### ISSUE TITLE
iPadOS 17.5.1 UaF race: heuristic strategy failed

### ISSUE THREAD

**Issue by chenaive** [palera1n/palera1n#533] opened 2024-12-16 16:58 UTC
### Device

iPad Pro 10.5

### Version

iPadOS 17.5.1

### Passcode?

- [ ] Passcode is enabled.

### Start going into detail..

Cable: USB-A to lightning
Platform: Ubuntu 24.04.1 in VMWare
palera1n file version: palera1n-linux-x86_64 
![图片](https://github.com/user-attachments/assets/646066d6-5f30-42a3-821f-cd68e2c26f0b)

I am using a ubuntu to run palera1n, and the ipad is set in DFU mode. 
But then go into a loop as : **UaF race: heuristic strategy failed, setup packet was not accepted**

### Familiarity with palera1n

- [ ] I am familiar with palera1n and how to use it!

### Familiarity with CLI

- [ ] I am familiar with the command-line!

**Comment by khcrysalis** [comment] 2024-12-20 02:39
This is a common issue amongst AMD systems, try connecting to a USB port directly on the motherboard. You can also retry a few times, perhaps with a different cable/port. If it still doesn’t work, you will need Intel, Apple Silicon, or an ARM platform.

Closing this issue as it's an issue we can't really control, sorry!

**Closed** 2024-12-20 02:40 UTC
Labels: wontfix, palera1n help

**Comment by karl-police** [comment] 2025-05-21 01:34
> AMD

Do we exactly know what the issue is? This seems very vague.

**Comment by karl-police** [comment] 2025-05-21 01:34
> This is a common issue amongst AMD systems, try connecting to a USB port directly on the motherboard. You can also retry a few times, perhaps with a different cable/port. If it still doesn’t work, you will need Intel, Apple Silicon, or an ARM platform.
> 
> Closing this issue as it's an issue we can't really control, sorry!

@khcrysalis 

Do we exactly know what the issue is? This seems very vague.
